name: Docker Build and Push

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      myservice:
        image: docker.pkg.github.com/nimmy-george/devpro_ica2/devpro_ica2:latest
        ports:
          - 8080:80
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Integration Tests
        run: |
          # Your integration test command here
